# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Report
    url: abstract/
    weight: 20
  - name: Slides
    url: slides/
    weight: 30
  - name: Results
    url: results/
    weight: 40
  - name: Poster
    url: poster/
    weight: 50
  - name: Code
    url: code/
    weight: 60

sidebar:
  - identifier: more
    name: Resources
    params:
      type: separator
    weight: 1
  - identifier: code
    name: "Code"
    pageRef: "/code"
    weight: 2
  - identifier: report
    name: "Full Report (PDF)"
    url: "uploads/report.pdf"
    external: true
    weight: 3